# Generated by Django 3.0.8 on 2020-07-09 09:03

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Site',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logo', models.ImageField(upload_to='logo-images/')),
                ('brand_title', models.CharField(max_length=100)),
                ('menu_option1', models.CharField(max_length=100)),
                ('menu_option2', models.CharField(max_length=100)),
                ('menu_option3', models.CharField(max_length=100)),
                ('data', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=150)),
                ('created', models.DateTimeField(default=datetime.datetime(2020, 7, 9, 9, 3, 39, 240732, tzinfo=utc))),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
