# Generated by Django 3.0.8 on 2020-07-11 16:11

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('constructor', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='site',
            name='brand_title',
        ),
        migrations.RemoveField(
            model_name='site',
            name='data',
        ),
        migrations.RemoveField(
            model_name='site',
            name='logo',
        ),
        migrations.RemoveField(
            model_name='site',
            name='menu_option1',
        ),
        migrations.RemoveField(
            model_name='site',
            name='menu_option2',
        ),
        migrations.RemoveField(
            model_name='site',
            name='menu_option3',
        ),
        migrations.AlterField(
            model_name='site',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2020, 7, 11, 16, 11, 39, 425607, tzinfo=utc)),
        ),
    ]
