# Generated by Django 3.0.8 on 2020-07-18 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('constructor', '0003_site_creator'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='template',
            name='img',
        ),
        migrations.AddField(
            model_name='template',
            name='sample_link',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
