# Generated by Django 3.0.8 on 2020-07-20 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('constructor', '0005_auto_20200720_0658'),
    ]

    operations = [
        migrations.AddField(
            model_name='site',
            name='template_name',
            field=models.CharField(default='grayscale', max_length=100),
            preserve_default=False,
        ),
    ]
