# Generated by Django 3.0.8 on 2020-07-24 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('constructor', '0006_site_template_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='site',
            name='link',
            field=models.CharField(max_length=225, null=True),
        ),
    ]
