# Generated by Django 3.0.8 on 2020-07-12 07:46

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('constructor', '0013_auto_20200711_1635'),
    ]

    operations = [
        migrations.AlterField(
            model_name='site',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2020, 7, 12, 7, 46, 26, 411447, tzinfo=utc)),
        ),
    ]
