# Generated by Django 3.0.8 on 2020-07-12 08:42

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('constructor', '0015_auto_20200712_0828'),
    ]

    operations = [
        migrations.AlterField(
            model_name='site',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2020, 7, 12, 8, 42, 19, 124450, tzinfo=utc)),
        ),
    ]
